/**
 * Offer-tier economics (market intents).
 * See consensus.ts + pricing.ts / docs/ECONOMICS.md.
 */

import {
  CANDLE_MINT_ATOMS,
  FLOWER_MINT_ATOMS,
  INCENSE_MINT_ATOMS,
  POW_CANDLE_BASE_ZERO_BITS,
  POW_FLOWER_BASE_ZERO_BITS,
  POW_INCENSE_BASE_ZERO_BITS,
  POW_PRAYER_BASE_ZERO_BITS,
  PRAYER_MINT_ATOMS,
} from './consensus.js';
import {
  WLOTUS_TARGET_USD_PER_TOKEN,
  WLOTUS_TARGET_USD_PER_BATON,
  pegTokenPricesUsd,
} from './pricing.js';

export const TOKENS_PER_REMINT = Number(FLOWER_MINT_ATOMS);

export const PRAYER_BASE_ZERO_BITS = POW_PRAYER_BASE_ZERO_BITS;
export const INCENSE_BASE_ZERO_BITS = POW_INCENSE_BASE_ZERO_BITS;
export const CANDLE_BASE_ZERO_BITS = POW_CANDLE_BASE_ZERO_BITS;
export const FLOWER_BASE_ZERO_BITS = POW_FLOWER_BASE_ZERO_BITS;

/** @deprecated */
export const NWLPOW_BASE_ZERO_BITS = INCENSE_BASE_ZERO_BITS;
/** @deprecated */
export const TEST_BASE_ZERO_BITS = CANDLE_BASE_ZERO_BITS;
/** @deprecated */
export const PROD_BASE_ZERO_BITS = FLOWER_BASE_ZERO_BITS;

export const PROD_TARGET_USD_PER_TOKEN = WLOTUS_TARGET_USD_PER_TOKEN;
export const PROD_TARGET_USD_PER_REMINT = WLOTUS_TARGET_USD_PER_BATON;

const peg = pegTokenPricesUsd();
export const CANDLE_TARGET_USD_PER_TOKEN = peg.candle;
export const INCENSE_TARGET_USD_PER_TOKEN = peg.incense;
export const PRAYER_TARGET_USD_PER_TOKEN = peg.prayer;

/** @deprecated */
export const TEST_TARGET_USD_PER_TOKEN = CANDLE_TARGET_USD_PER_TOKEN;
/** @deprecated */
export const NWLPOW_TARGET_USD_PER_TOKEN = INCENSE_TARGET_USD_PER_TOKEN;

export const TEST_POW_LEADING_ZERO_BYTES = 1;
export const TEST_INITIAL_MINT_ATOMS = 1_000_000n;
export const TEST_POW_BATON_COUNT = 4;

export const TEST_TOKEN_TICKER = 'CANDLE';
export const TEST_TOKEN_NAME = 'Candle';
export const NWLPOW_TOKEN_TICKER = 'INCENSE';
export const NWLPOW_TOKEN_NAME = 'Incense';
export const PRAYER_TOKEN_TICKER = 'PRAYER';
export const PRAYER_TOKEN_NAME = 'Prayer';

export const TEST_TARGET_USD_PER_REMINT =
  CANDLE_TARGET_USD_PER_TOKEN * Number(CANDLE_MINT_ATOMS);
export const NWLPOW_TARGET_USD_PER_REMINT =
  INCENSE_TARGET_USD_PER_TOKEN * Number(INCENSE_MINT_ATOMS);
export const PRAYER_TARGET_USD_PER_REMINT =
  PRAYER_TARGET_USD_PER_TOKEN * Number(PRAYER_MINT_ATOMS);

export {
  PRAYER_MINT_ATOMS,
  INCENSE_MINT_ATOMS,
  CANDLE_MINT_ATOMS,
  FLOWER_MINT_ATOMS,
};
