#!/usr/bin/env tsx
/**
 * Generate a fresh mainnet genesis keypair and write .env (gitignored).
 * Prints the funding address — send ≥ 200 XEC, then run create-test-token.
 */
import { randomBytes } from 'node:crypto';
import { writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { Wallet } from 'ecash-wallet';
import { toHex } from 'ecash-lib';
import { createChronik } from '../src/network/createChronik.js';
import { MAINNET_CHRONIK_URLS } from '../src/network/chronikUrls.js';

async function main(): Promise<void> {
  const force = process.argv.includes('--force');
  const envPath = resolve(process.cwd(), '.env');
  if (existsSync(envPath) && !force) {
    console.error(
      `.env already exists. Pass --force to overwrite, or fund the existing address.`,
    );
    process.exit(1);
  }

  const chronik = await createChronik('closest');
  const sk = randomBytes(32);
  const wallet = Wallet.fromSk(sk, chronik);
  await wallet.sync();

  const body = [
    '# Generated by npm run new-wallet — DO NOT COMMIT',
    `CHRONIK_URL=${MAINNET_CHRONIK_URLS[0]}`,
    `GENESIS_SK_HEX=${toHex(sk)}`,
    `GENESIS_ADDRESS=${wallet.address}`,
    '',
  ].join('\n');
  writeFileSync(envPath, body, { mode: 0o600 });

  const pending = {
    network: 'mainnet',
    genesisAddress: wallet.address,
    balanceSats: wallet.balanceSats.toString(),
    minSuggestedXec: 200,
    nextStep: 'Send ≥ 200 XEC to genesisAddress, then: npm run create-test-token',
    chronikUrls: [...MAINNET_CHRONIK_URLS],
  };
  writeFileSync(
    resolve(process.cwd(), 'deployments/pending-funding.json'),
    `${JSON.stringify(pending, null, 2)}\n`,
  );

  console.log(JSON.stringify(pending, null, 2));
  console.log(`\nWrote ${envPath} (gitignored) and deployments/pending-funding.json`);
}

main().catch(err => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
