export {
  ALTAR_SEP,
  MEMORIAL_NOTE_MAX_BYTES,
  MEMORIAL_NOTE_MAX_CHARS,
  altarHonorificLabel,
  emptyAltarFields,
  encodeAltarNote,
  formatAltarDateInput,
  formatAltarPersonName,
  formatDeathDateInput,
  isAltarPackedNote,
  memorialDisplayName,
  normalizeAltarHonorific,
  parseAltarNote,
  validateAltarFields,
  type AltarFields,
  type AltarHonorific,
  type AltarLocale,
} from '../../../../src/offering/altarFields.js';
